global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: rabbitmq
    static_configs:
      - targets: ["rabbitmq:15692"]
  - job_name: awips-ingest
    static_configs:
      - targets: ["ingest-awips:2112"]
  - job_name: awips-parse
    static_configs:
      - targets: ["parse-awips:2112"]